### ISSUE TITLE
Set the data format between front-backend and backend-training model.

### ISSUE THREAD

**Issue by baldandbrave** [baldandbrave/RecSysCOEN6313#10]
We have the data format of the training data. Please @Dvangelion set the data format between the backend and training model.

**Comment by Dvangelion** [comment]
The model outputs the probability of user behaviours. i.e., {"adding to cart":0.5, "purchase":0.5}. I'll let you know after training is done.

**Comment by 4ban** [comment]
Guys @baldandbrave @Dvangelion @Lyncis @smcheraghi , we need to specify the REST API queries that we could start preparing the frontend for the backend. 

Example of  queries that the front should send:

| HTTP request 	|     Action    	| Example                        	|
|:----:	        |:----:	                |:----:                                                |
| GET          	| Get all goods 	| http://backend.com/api/goods   	|
| GET          	| Get one good  	| http://backend.com/api/goods/1 	|
| POST         	| Create good   	| http://backend.com/api/goods   	|
| DELETE       	| Delete good   	| http://backend.com/api/goods/1 	|
| PUT          	| Update good   	| http://backend.com/api/goods/1 	|

And example of data that will return for every query:
For example GET one good should return for front-end JSON like this:
```JSON
{ 
"id": 1, 
"title" : 
"Santa pants", 
"cost": 99999, 
"recommendations" : [{
    "id": 2,
    "id": 3,
    "id": 4
    }]
}
```

After that I can create a fake json server that will send me the data like this and independently work on front-end
